export default {
    SOMETHING_WENT_WRONG: 'Something Went Wrong',
    NOT_FOUND: (entity: string) => `Not Found ${entity}`,
    TOO_MANY_REQUESTS: 'Too many requests: please wait for some time and try again.',
    PASSWORD_ENCRYPTION_ERROR: 'Error while encrypting password',
    INVALID_CREDENTIALS: (entity: string) => `Invalid credentials for ${entity}`,
    INVALID: (entity: string) => `Invalid ${entity}`,
    LOGOUT: 'Logout successful',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    LOGIN: 'Login successful',
    SUCCESS: (entity: string) => `${entity} successfully`,
    UNAUTHORIZED: 'Unauthorized Access',
    CONFIRM_PASS_NEW_PASS_NOT_MATCH: 'Confirm password does not match with new password',
    OLD_PASS_NEW_PASS_MATCH: 'Old password and new password cannot be the same',
    OLD_PASS_NOT_MATCH: 'Old password does not match',
    RESET_PASSWORD_LINK_SENT: 'Password reset link sent to your email address',
    UPDATE_SUCCESS: (entity: string) => `${entity} updated successfully`,
    TOKEN_EXPIRED: 'Token expired',
    ALREADY_EXIST: (entity: string) => `${entity} already exists`,
    CREATED: (entity: string) => `${entity} created successfully`,
    DELETED: (entity: string) => `${entity} deleted successfully`,
    FORBIDDEN: (entity: string) => `Forbidden access to ${entity}`,
    FETCHED: (entity: string) => `${entity} fetched successfully`,
    FORBIDDEN_ROLE: 'Forbidden: You do not have the required role',
    FORBIDDEN_PERMISSION: 'Forbidden: You do not have the required permission',
    BAD_REQUEST: (message: string) => `Bad Request: ${message}`,
    EMAIL_FIELD_UPDATE_RESTRICTED: 'Email field cannot be updated',
    PHONE_FIELD_UPDATE_RESTRICTED: 'Phone field cannot be updated'
} as const
